apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: ${cert_issuer_url}
    email: ${email}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudDNS:
            project: ${provider}
        selector:
          dnsZones:
            - "${dns}"
            - "*.${dns}"