apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-gcp-nodepool
spec:
  weight: 10
  template:
    spec:
      nodeClassRef:
        name: karpenter-gcp-nodeclass
        kind: GCENodeClass
        group: karpenter.k8s.gcp
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand", "spot"]

        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["e2-standard-2","e2-standard-4","e2-highmem-2","e2-highcpu-2","e2-highcpu-4","e2-highcpu-8"]

        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]

        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ${ZONES}