#!/bin/sh

gcloud container clusters get-credentials $cluster_name --region=$region --project=$provider_id

kubectl get cronjob -o=jsonpath="{range .items[*]}{'\n'}{.metadata.name}{': '}{range .spec.jobTemplate.spec.template.spec.containers[*]}{.image}{end}{end}" -n $namespace > cronImageValues.yaml
cat cronImageValues.yaml