apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "${service_name}-secrets-application"
  namespace: ${namespace}
spec:
  provider: gcp
  secretObjects:
    - secretName: "${service_name}-application-secrets"
      type: Opaque
      data:
      %{~ for k,v  in jsondecode(secrets) }
      - objectName: "${v.value}"
        key: "${v.key}"
      %{~ endfor ~}
    %{~ for ingress in ingress_with_secret ~}
    - secretName: "tls-secret-${ingress.host}"
      type: kubernetes.io/tls
      data:
        - objectName: "${ingress.cloud_secret.tls_crt_key}"
          key: tls.crt
        - objectName: "${ingress.cloud_secret.tls_key_key}"
          key: tls.key
    %{~ endfor ~}

  parameters:
    secrets: |
      %{~ for k,v in jsondecode(secrets) }
      - resourceName: "projects/${provider_id}/secrets/${v.value}/versions/latest"
        fileName: "${v.value}"
      %{~ endfor ~}
      %{~ for ingress in ingress_with_secret ~}
      - resourceName: "projects/${provider_id}/secrets/tls-secret-${ingress.host}/versions/latest"
        fileName: "${ingress.cloud_secret.tls_crt_key}"
      - resourceName: "projects/${provider_id}/secrets/tls-secret-${ingress.host}/versions/latest"
        fileName: "${ingress.cloud_secret.tls_key_key}"
      %{~ endfor ~}
