apiVersion: v1
kind: Pod
metadata:
  name: psql-init-${rds_name}
  namespace: ${namespace}
spec:
  containers:
    - name: psql-init-role
      image: jbergknoff/postgresql-client
      args: ["postgresql://${db_user}@${db_host}:${db_port}/${db_name}", "-f", "/etc/config/db-init.sql"]
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: ${master_secret_name}
              key: password
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/config
  volumes:
    - name: secret-volume
      secret:
        secretName: ${rds_name}
  restartPolicy: Never