apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-dns
  namespace : cert-manager
spec:
  secretName: wildcard-dns
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.${dns}"
  dnsNames:
    - "${dns}"
    - "*.${dns}"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"  # permit replication
      replicator.v1.mittwald.de/replication-allowed-namespaces: "*"  # comma separated list of namespaces or regular expressions
