apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: general
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  role: arn:aws:iam::${ACCOUNT_ID}:instance-profile/KarpenterNodeInstanceProfile
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}
