apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: general
spec:
  template:
    metadata:
      labels:
        type: general
    spec:
      nodeClassRef:
        name: general
        kind: EC2NodeClass
  limits:
    cpu: ${CPU_LIMIT}
    memory: ${MEMORY_LIMIT}
    disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
