kubernetes:
  host: https://kubernetes.default

reloader:
  autoReloadAll: false
  isArgoRollouts: false
  isOpenshift: false
  watchGlobally: true
  enableHA: false
  readOnlyRootFileSystem: false
  legacy:
    rbac: false
  matchLabels: {}
  deployment:
    replicas: 1
    revisionHistoryLimit: 2

    securityContext:
      runAsNonRoot: true
      runAsUser: 65534

    labels:
      provider: stakater
      group: com.stakater.platform
      version: v1.0.60
    image:
      name: ghcr.io/stakater/reloader
      tag: v1.0.60
      pullPolicy: IfNotPresent

  rbac:
    enabled: true
  serviceAccount:
    create: true
