apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-application
  namespace: ${namespace}
spec:
  provider: aws
  secretObjects:
    - secretName: application-secrets
      type: Opaque
      data:
      %{~ for secret in secrets }
      - objectName: "${secret}"
        key: "${secret}"
      %{~ endfor ~}

  parameters:
    objects: |
      %{~ for secret in secrets }
      - objectName: "${secret}"
        objectType: "secretsmanager"
      %{~ endfor ~}