initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id= ${access_key}
      aws_secret_access_key= ${secret_access_key}
configuration:
  backupStorageLocation:
    - name: ${cluster_name}-backup-location
      bucket: ${bucket_name}
      provider: aws
      config:
        region: ${region}

deployNodeAgent: true
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  privileged: false
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

snapshotsEnabled: false

defaultVolumesToFsBackup: true