configuration:
  provider: aws
  backupStorageLocation:
    name: default
    bucket: ${bucket_name}
    config:
      region: ${region}
      s3ForcePathStyle: true

  volumeSnapshotLocation:
    name: default
    config:
      region: ${region}

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=${access_key}
      aws_secret_access_key=${secret_access_key}