apiVersion: v1
kind: Pod
metadata:
  name: psql-init-${rds_name}
  namespace: ${namespace}
spec:
  containers:
    - name: psql-init-role
      image: jbergknoff/postgresql-client
      args:
        %{~ if enable_ssl ~}
        - "postgresql://${db_user}@${db_host}:${db_port}/${db_name}?sslmode=require&sslcert=/etc/ssl/client.pem&sslkey=/etc/ssl/private.pem"
        %{~ else ~}
        - "postgresql://${db_user}@${db_host}:${db_port}/${db_name}"
        %{~ endif ~}
        - "-f"
        - "/etc/config/db-init.sql"
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: ${master_secret_name}
              key: password
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/config
        %{~ if enable_ssl ~}
        - name: ssl-volume
          mountPath: /etc/ssl
        %{~ endif ~}
  #  initContainers:
  #    - name: psql-init-db
  #      image: jbergknoff/postgresql-client
  #      args: ["postgresql://${db_user}@${db_host}:${db_port}/postgres", "-f", "/etc/config/db-init.sql"]
  #      env:
  #        - name: PGPASSWORD
  #          valueFrom:
  #            secretKeyRef:
  #              name: ${master_secret_name}
  #              key: password
  #      volumeMounts:
  #        - name: config-volume
  #          mountPath: /etc/config
  volumes:
    - name: secret-volume
      secret:
        secretName: db-secret-${rds_name}
    %{~ if enable_ssl ~}
    - name: ssl-volume
      secret:
        secretName: ${name_prefix}-ssl-certs
        defaultMode: 0o600
    %{~ endif ~}
  restartPolicy: Never