apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${cluster_name}-cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook
rules:
  - apiGroups:
      - acme.oracle.com
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook
subjects:
  - kind: ServiceAccount
    name: ${cluster_name}-cert-manager
    namespace: cert-manager
