apiVersion: v1
kind: Secret
metadata:
  name: oci-profile
  namespace: cert-manager
type: Opaque
stringData:
  tenancy: "${tenancy}"
  user: "${user}"
  region: "${region}"
  fingerprint: "${fingerprint}"
  privateKey: |
  ${indent(4, private_key)} 
  privateKeyPassphrase: ""