apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${secret_name}
  namespace: ${namespace}
spec:
  secretName: ${secret_name}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.${dns}"
  dnsNames:
    - "*.${dns}" 