#!/bin/sh

az aks get-credentials --resource-group $resource_group_name --name "$cluster_name"-aks --admin

kubectl get cronjob -o=jsonpath="{range .items[*]}{'\n'}{.metadata.name}{': '}{range .spec.jobTemplate.spec.template.spec.containers[*]}{.image}{end}{end}" -n $namespace > cronImageValues.yaml
cat cronImageValues.yaml