#!/bin/sh

aws eks update-kubeconfig --region $region --name $cluster_name


kubectl get deployment -o=jsonpath="{range .items[*]}{'\n'}{.metadata.name}{': '}{range .spec.template.spec.containers[*]}{.image}{end}{end}" -n $namespace > imageValues.yaml
cat imageValues.yaml