apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  namespace: cortex
  labels:
    app: kube-prometheus-stack
    heritage: Helm
    release: prometheus
  name: ${cluster_name}-cortex-alerts
spec:
  groups:
    - name: cortex-alerts
      rules:
        # Alert if cortex queryfrontend replica is below the threshold
        - alert: ${cluster_name}_cortex_queryfrontend_replica_below_${queryfrontend_replica_threshold}
          annotations:
            description: "${cluster_name} cortex queryfrontend replica count is below ${queryfrontend_replica_threshold} of the allocated replica."
          expr: kube_deployment_status_replicas_available{namespace="cortex", deployment="cortex-query-frontend"} < ${queryfrontend_replica_threshold}
          labels:
            severity: critical
            servicealert: "true"
            cluster: ${cluster_name}
        # Alert if cortex distributor replica is below the threshold
        - alert: ${cluster_name}_cortex_distributor_replica_below_${distributor_replica_threshold}
          annotations:
            description: "${cluster_name} cortex distributor replica count is below ${distributor_replica_threshold} of the allocated replica."
          expr: kube_deployment_status_replicas_available{namespace="cortex", deployment="cortex-distributor"} < ${distributor_replica_threshold}
          labels:
            severity: critical
            servicealert: "true"
            cluster: ${cluster_name}

        # Alert if cortex ingester replica is below the threshold
        - alert: ${cluster_name}_cortex_ingester_replica_below_${ingester_replica_threshold}
          annotations:
            description: "${cluster_name} cortex ingester replica count is below ${ingester_replica_threshold} of the allocated replica."
          expr: kube_statefulset_status_replicas_available{namespace="cortex", statefulset="cortex-ingester"} < ${ingester_replica_threshold}
          labels:
            severity: critical
            servicealert: "true"
            cluster: ${cluster_name}

        # Alert if cortex querier replica is below the threshold
        - alert: ${cluster_name}_cortex_querier_replica_below_${querier_replica_threshold}
          annotations:
            description: "${cluster_name} cortex querier replica count is below ${querier_replica_threshold} of the allocated replica."
          expr: kube_statefulset_status_replicas_available{namespace="cortex", statefulset="cortex-querier"} < ${querier_replica_threshold}
          labels:
            severity: critical
            servicealert: "true"
            cluster: ${cluster_name}