apiVersion: v1
kind: Pod
metadata:
  name: mysql-init-${rds_name}
  namespace: ${namespace}
spec:
  containers:
    - name: mysql-init-role
      image: imega/mysql-client
      command: [ "mysql" ]
      args: [ "-h", "${db_host}", "-u", "${db_user}", "-p$(MYSQL_ROOT_PASSWORD)", "-e", "source /etc/config/db-init.sql" ]
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${master_secret_name}
              key: password
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/config
  volumes:
    - name: secret-volume
      secret:
        secretName: ${rds_name}
  restartPolicy: Never