#!/bin/sh

oci ce cluster create-kubeconfig --cluster-id $cluster_id --file $HOME/.kube/config --region $region --token-version 2.0.0  --kube-endpoint PUBLIC_ENDPOINT

kubectl get cronjob -o=jsonpath="{range .items[*]}{'\n'}{.metadata.name}{': '}{range .spec.jobTemplate.spec.template.spec.containers[*]}{.image}{end}{end}" -n $namespace > cronImageValues.yaml
cat cronImageValues.yaml