apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "${service_name}-secrets-application"
  namespace: ${namespace}
spec:
  provider: oci
  secretObjects:
    - secretName: "${service_name}-application-secrets"
      type: Opaque
      data:
      %{~ for k,v  in jsondecode(secrets) }
      - objectName: "${v.value}"
        key: "${v.key}"
      %{~ endfor ~}
  parameters:
    secrets: |   
      %{~ for k,v in jsondecode(secrets) }
      - name: "${v.value}"
      %{~ endfor ~}
    authType: instance    
    vaultId: "${vault_ocid}"